name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - jerboas86
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report 💚!
  - type: textarea
    id: bug_description
    attributes:
      label: Describe the bug?
      description: A clear and concise description of what the bug is.
      placeholder: Bug description...
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Describe the expected behavior?
      description: A clear and concise description of what you expected to happen.
      placeholder: Expected behavior description...
    validations:
      required: true
  - type: textarea
    id: reproduce_steps
    attributes:
      label: Describe the steps to repoduce the bug?
      description: Steps required to do to see the bug.
      placeholder: |
        reproduction steps...
        1.
        2.
        3.
    validations:
      required: true
  - type: dropdown
    id: form_factor
    attributes:
      label: What form factors are you seeing the problem on?
      multiple: true
      options:
        - Mobile
        - Tablet
        - Desktop
        - Other
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Other
    validations:
      required: true
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context or infos about the problem here.
      placeholder: Others infos...
    validations:
      required: false
