name: Feature Request
description: Suggest an idea for this project without a plan for implementation
title: "[Feature Request]: "
labels: ["feature", "triage"]
assignees:
  - jerboas86
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest an idea for this project 💜!
  - type: textarea
    id: problem_description
    attributes:
      label: Describe your problem
      description: Is your feature request related to a problem? Please describe your use-case.
      placeholder:
        A clear and concise description of what the problem is. Ex. I'm always
        frustrated when [...]"
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe your ideal solution
      description: |
        Describe the solution you'd like
      placeholder: |
        A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Workarounds or alternatives
      description: Describe alternatives you've considered
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      placeholder: Something to add...
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: true
